print("What is your name?\n")
name=input()
print("How old are you?\n")
age=input()
print("Where do you live?\n")
city=input()
print("Hello, ", name, '\n')
print("Your age is ", age, '\n')
print("You live in ", city, '\n')